spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_auth_service
    username: root
    password: password@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

application:
  jwt:
    secret: "UHZHaWdIZnFWQ0tlSkxZZnRIaUtoaG1qaWZJYm1FcTQ="
    expiration: 28800 # in seconds